FROM ghcr.io/jim60105/whisperx:no_model

RUN pip install fastapi "uvicorn[standard]"

USER root
RUN apt-get update && apt-get install -y lsof  \
    && apt-get install -y curl && apt-get install -y procps

USER 1001
COPY api /app

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000", "--app-dir", "/app"]
